apps/applications/urls.py
from django.urls import path
from applications.views import AddApplicationView, EqModelsView, DetailsApplicationView, EquipmentExcelView, AllEquipmentExcelView
from applications.views import EditApplicationView, TestTaskView, SnEqView, ApplicationHistoryView, SpareExcelView, GetOrganizationView
from applications.views import GetContactsView, SpareLoadView
from applications.views import GetSpareModels, GetModelPNs, GetSparesList, InstalledBaseExcel, GetEquipmentsInEdit, ReadingEmailSelver
from applications.views import ListApplicationView, NewAddApplicationView, TestView, EditCommentView, DeleteCommentView
# , ListApplicationView
from applications.api.api import *

urlpatterns = [
    path('add/', AddApplicationView, name = 'add-application'),
    path('edit/<int:application_id>', EditApplicationView, name = 'edit-application'),
    path('models/', EqModelsView, name = 'models'),
    path('details/<int:application_id>', DetailsApplicationView, name = 'app-details'),
    path('history/<int:application_id>/<int:type>', ApplicationHistoryView, name = 'app-history'),
    # path('logs/<int:application_id>', ApplicationLogsView, name = 'app-logs'),
    path('comment/edit/<int:comment_id>/<int:link_type>', EditCommentView, name = 'edit-comment'),
    path('comment/delete/<int:comment_id>/<int:link_type>', DeleteCommentView, name = 'delete-comment'),
    # path('list/', ListApplicationView, name = 'app-list'),
    # path('sn_eqs/<str:sn>', SnEqView, name = 'sn-eqs'),
    path('eq_excel/', EquipmentExcelView, name = 'eq-excel'),
    path('all_eq_excel/', AllEquipmentExcelView, name = 'all-eq-excel'),
    path('installed_base/', InstalledBaseExcel, name = 'installed-base'),
    path('spare_models/', GetSpareModels, name = 'spare-models'),
    path('model_pns/', GetModelPNs, name = 'model-pns'),
    path('spare_excel/', SpareExcelView, name = 'spare-excel'),
    path('spare_load/', SpareLoadView, name = 'spare-load'),
    path('get_organization/', GetOrganizationView, name = 'get-organization'),
    path('get_spares_list/', GetSparesList, name = 'get-spares-list'),
    path('get_contacts/', GetContactsView, name = 'get-contacts'),
    path('get_eqs_in_edit/', GetEquipmentsInEdit, name = 'get-eqs-in-edit'),

    path('read_emails/', ReadingEmailSelver, name = 'read-emails'),
    # path('test_task/', TestTaskView, name = 'test-task'),

    path('apps_list/', ListApplicationView, name = 'app-list'),
    # path('new_add/', NewAddApplicationView, name = 'new-add-application'),

    # path('test/', TestView),

    path('api/app_priorities/', AppPrioritiesListAPIView.as_view()),
    path('api/app_statuses/', AppStatusesAPIView.as_view()),
    path('api/clients_equipments/<int:client_id>', GetClientsEquipmentsAPIView.as_view()),

    path('api/list/', ApplicationsListAPIView.as_view(), name = 'applications-list'),
    path('api/clients_contacts/<int:client_id>', GetClientsContactsAPIView.as_view()),
    path('api/add/', AddApplicationAPIView.as_view(), name = 'add-application-api'),
    path('api/list_to_excel/', ApplicationsExcelAPIView.as_view(), name = 'applications-to-excel'),
    path('api/edit/<int:application_id>', EditApplicationAPIView.as_view(), name = 'edit-application-api'),
    path('api/edit/<int:application_id>/<int:status_id>', EditDoneApplicationAPIView.as_view(), name = 'edit-done-application-api'),
    path('api/edit/documents/<int:application_id>', ApplicationDocumentsAPIView.as_view(), name = 'add-app-docs-api'),
    path('api/edit/comments/<int:application_id>', ApplicationCommentsAPIView.as_view(), name = 'add-app-comm-api'),
    path('api/comment/<int:comment_id>', AppCommentAPIView.as_view(), name = 'edit-app-comm-api'),
    path('api/history/<int:application_id>', ApplicationHistoryAPIView.as_view()),
    path('api/logs/<int:application_id>', ApplicationLogsAPIView.as_view()),
    path('api/spares/<int:application_id>', AppSpareAPIView.as_view(), name = 'add-app-spare-api'),

    path('api/client/contracts/', GetClientsContractsAPIView.as_view(), name = 'clients-contracts-api'),
    path('api/client/contracts/excel/', ClientsContractsExcelAPIView.as_view(), name = 'clients-contracts-excel-api'),

    path('api/details/<int:application_id>', ApplicationDetailsAPIView.as_view(), name = 'app-details-api'),
]

urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url

from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView

from integrator.apps.api_services import *

urlpatterns = [
    path('', include('main.urls')),
    path('', include('login.urls')),
    path('applications/', include('applications.urls')),
    path('equipments/', include('equipments.urls')),
    path('spares/', include('spares.urls')),
    path('contracts/', include('contracts.urls')),
    path('accounts/', include('accounts.urls')),
    path('admin/', include('admin.urls')),
    path('articles/', include('articles.urls')),
    path("select2/", include("django_select2.urls")),
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/docs/', SpectacularSwaggerView.as_view(url_name='schema'), name='docs'),
    path('api/engineers/', EngineersListAPIView.as_view()),
    # path('admin/', admin.site.urls),
    # url(r'^_nested_admin/', include('nested_admin.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

apps/applications/models.py
import os
from datetime import datetime

from django.db import models
from django.db.models import OuterRef, F
from django.conf import settings
from django.urls import reverse

from io import BytesIO
from django.core.files import File
from ckeditor.fields import RichTextField
from django.db.models.signals import post_save
from django.dispatch import receiver

from bs4 import BeautifulSoup

import barcode                      # additional imports
from barcode.writer import ImageWriter

from pytils import translit

from accounts.models import OrganizationContactModel
from contracts.models import ContractEquipmentModel
from equipments.models import EquipmentModel
from spares.models import SpareModel

from integrator.apps.functions import send_email, send_telegram

def file_name(instance, filename):
    path = 'applications/' + str(instance.application.pk) + '/'
    ext = filename.split('.')[-1]
    filename = datetime.now().strftime("%d%m%Y%H%M%S") + '.' + ext
    return os.path.join(path, filename)

def file_conf(instance, filename):
    path = 'equipments/' + str(instance.equipment.pk) + '/'
    ext = filename.split('.')[-1]

    filename =  translit.slugify(filename.replace('.' + ext, ''))
    if ext:
        filename = filename + '.' + ext

    return os.path.join(path, filename)

def file_contract(instance, filename):
    path = 'contracts/' + str(instance.contract.pk) + '/'
    ext = filename.split('.')[-1]
    if ext:
        filename = filename.replace('.' + ext, '')
    filename =  translit.slugify(filename)
    if ext:
        filename = filename + '.' + ext
    return os.path.join(path, filename)

class AppPriorityModel(models.Model):
    name = models.CharField('Наименование', max_length = 300)
    priority = models.IntegerField('Приоритет', default = 0)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Приоритет заявки'
        verbose_name_plural = 'Приоритеты заявок'
        ordering = ['priority', 'name']

class EquipmentConfigModel(models.Model):
    from integrator.apps.validators import validate_format, validate_size_10

    document = models.FileField('Файл', upload_to = file_conf, validators = [validate_format, validate_size_10])
    equipment = models.ForeignKey(EquipmentModel, verbose_name = 'Оборудование', on_delete = models.CASCADE, related_name = "equipconf")

    def __str__(self):
        return str(self.equipment)

    class Meta:
        verbose_name = 'Файл конфигурации'
        verbose_name_plural = 'Файлы конфигурации оборудования'


class StatusModel(models.Model):
    name = models.CharField('Наименование', max_length = 300)
    priority = models.IntegerField('Приоритет', default = 0)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Статус заявки'
        verbose_name_plural = 'Статусы заявок'
        ordering = ['priority', 'name']

class ApplicationModel(models.Model):
    priority = models.ForeignKey(AppPriorityModel, verbose_name = 'Приоритет заявки', on_delete = models.PROTECT, related_name = "priorities", null = True)
    equipment = models.ForeignKey(ContractEquipmentModel, verbose_name = 'Оборудование', on_delete = models.PROTECT, related_name = "equipments", null = True)
    problem = models.TextField('Описание проблемы')
    contact = models.ForeignKey(OrganizationContactModel, verbose_name = 'Контактное лицо', on_delete = models.SET_NULL, related_name = "appcontact", null = True)
    client = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name = 'Заказчик', on_delete = models.PROTECT, related_name = "appclients", null = True)
    engineer = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name = 'Инженер', on_delete = models.PROTECT, related_name = "engineers", null = True, blank = True)
    pubdate = models.DateTimeField('Дата создания', auto_now_add = True)
    status = models.ForeignKey(StatusModel, verbose_name = 'Статус заявки', on_delete = models.PROTECT, null = True)
    creator = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name = 'Создано', on_delete = models.PROTECT, related_name = "creators", null = True)
    changed = models.BooleanField('Оборудование изменено', default = False)

    def __str__(self):
        return str(self.id)

    def get_absolute_url(self):
        return reverse('app-details', kwargs = {'application_id': int(self.pk)})

    class Meta:
        verbose_name = 'Заявка'
        verbose_name_plural = 'Заявки'
        ordering = ['status__priority', '-id',]

class AppDocumentsModel(models.Model):
    from integrator.apps.validators import validate_format, validate_size

    name = models.CharField('Наименование файла', max_length = 300, blank = True)
    document = models.FileField('Файл', upload_to = file_name, validators = [validate_format, validate_size])
    application = models.ForeignKey(ApplicationModel, verbose_name = 'Заявка', on_delete = models.CASCADE, related_name = "documents", null = True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.name:
            self.name = self.document.name
        super().save(*args, **kwargs)

class AppStatusModel(models.Model):
    status = models.ForeignKey(StatusModel, verbose_name = 'Статус заявки', on_delete = models.SET_NULL, related_name = "statuses", null = True)
    application = models.ForeignKey(ApplicationModel, on_delete = models.CASCADE, related_name = "appstatuses", null = True)
    pubdate = models.DateTimeField('Дата создания', auto_now_add = True)

    def __str__(self):
        return str(self.application)

    class Meta:
        ordering = ['-pubdate']

class AppCommentModel(models.Model):
    text = RichTextField('Комментарий', config_name = 'small')
    hide = models.BooleanField('Скрыть комментарий от клиента', default = False)
    pubdate = models.DateTimeField('Дата создания', auto_now_add = True)
    email_date = models.DateTimeField('Дата создания', null = True, blank = True)
    edited = models.BooleanField('Комментарий был отредактирован', default = False)
    application = models.ForeignKey(ApplicationModel, verbose_name = 'Заявка', on_delete = models.CASCADE, related_name = "comments")
    author = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name = 'Автор', on_delete = models.SET_NULL, null = True, related_name = "authors")

    def __str__(self):
        return self.text

    def save(self, *args, **kwargs):
        method_type = 'created' if not self.pk else 'updated'
        super(AppCommentModel, self).save(*args, **kwargs)

        comments_send_messages(self, method_type)

    def delete(self, *args, **kwargs):
        super(AppCommentModel, self).delete(*args, **kwargs)

        comments_send_messages(self, 'deleted')

    class Meta:
        ordering = ['-pubdate']

def comments_send_messages(comment, method_type):
    application = ApplicationModel.objects.annotate(
        email = OrganizationContactModel.objects.filter(id = OuterRef('contact_id'))[:1].values('email'),
        engineer_email = F('engineer__email')).get(id = comment.application_id)

    to_emails = []
    history = []
    host = settings.ALLOWED_HOSTS[1]
    params = {
        'id': application.id,
        'url': 'https://' + host + application.get_absolute_url(),
        'status': comment.text.strip(),
        'type': 'comment'
    }
    text = ''

    if not comment.email_date:
        to_emails.append(application.email)
    if application.engineer:
        to_emails.append(application.engineer_email)

    title = ' комментарий к заявке № ' + str(application.id)

    if method_type == 'created':
        title = 'Добавлен' + title
        text_part = 'о добавлении'
    elif method_type == 'updated':
        title = 'Изменен' + title
        text_part = 'об изменении'
        params['type'] = 'comment_edit'
    else:
        title = 'Удален' + title
        text_part = 'об удалении'
        params['type'] = 'comment_delete'

    if to_emails:
        if send_email(params = params, title = title, send_to = to_emails):
            text = 'Отправлено сообщение ' + text_part + ' комментария "' + comment.text + '" на электронную почту'
        else:
            text = 'Не удалось отправить сообщение ' + text_part + ' комментария "' + comment.text + '" на электронную почту'
        history.append({'type': 4, 'text': text, 'application': application, 'author': comment.author})

    telegram_text = comment.text.replace('&nbsp;', ' ').replace('<ul>', '').replace('</ul>', '').replace('<ol>', '').replace('</ol>', '')
    Parse = BeautifulSoup(telegram_text, 'html.parser')

    tags = ['p', 'span', 'blockquote', 'sup', 'sub', 'li', 'a', 'div']

    all_the_tags = Parse.find_all()
    for tag in all_the_tags:
        if tag.has_attr('style'):
            del tag.attrs['style']
        if tag.name == "br":
            tag.replace_with("\n")
        if tag.name in tags:
            if tag.name == 'p' or tag.name == 'li':
                if tag.string:
                    tag.string = tag.string + "\n"
            tag.unwrap()

    telegram_text = str(Parse).strip()

    params['status'] = telegram_text
    params['author'] = comment.author.get_full_name() or comment.author.email

    if send_telegram(params = params):
        text = 'Отправлено сообщение ' + text_part + ' комментария в телеграм-канал'
    else:
        text = 'Не удалось отправить сообщение ' + text_part + ' комментария в телеграм-канал'
    history.append({'type': 4, 'text': text, 'application': application, 'author': comment.author})

    history_instance = [AppHistoryModel(**row) for row in history]
    AppHistoryModel.objects.bulk_create(history_instance)

class AppSpareModel(models.Model):
    spare = models.ForeignKey(SpareModel, verbose_name = 'Запчасть', on_delete = models.CASCADE, related_name = "appspare")
    application = models.ForeignKey(ApplicationModel, verbose_name = 'Заявка', on_delete = models.CASCADE, related_name = "appeqspare")

templates/applications/edit.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Редактирование заявки{% endblock title %}

{% block page-title %}Заявка № {{ data.application.id }}{% endblock page-title %}
{% block content %}
<section>
  <div class="container">
    <a class="back-link" href="{% url 'app-list' %}">Назад</a>
    <div class="justify-between pb-40">
      <div class="block-content w-50">
        <form method="POST" enctype="multipart/form-data" class="edit-app">
          {% csrf_token %}
        <p><b>Дата создания:</b> {{ data.application.formatted_date }}</p>
        {% if data.application.status_id != 4 %}
          <input type="hidden" name="appstatuses-TOTAL_FORMS" value="1" id="id_appstatuses-TOTAL_FORMS">
          <input type="hidden" name="appstatuses-INITIAL_FORMS" value="1" id="id_appstatuses-INITIAL_FORMS">
          <input type="hidden" name="appstatuses-MIN_NUM_FORMS" value="0" id="id_appstatuses-MIN_NUM_FORMS">
          <input type="hidden" name="appstatuses-MAX_NUM_FORMS" value="1" id="id_appstatuses-MAX_NUM_FORMS">
          {{ formset.forms.0.id }}
          <p class="flex">
            <label for="id_appstatuses-0-status"><b>Статус заявки:</b> {% if data.application.status_id == 6 or data.application.status_id == 1 %}{{ data.application.status_name }}{% endif %}</label>
            {{ formset.forms.0.status.errors }}
            {{ formset.forms.0.status }}
          </p>
          <p class="flex">
            <label for="id_priority"><b>Приоритет заявки:</b></label>
            {{ form.priority.errors }}
            {{ form.priority }}
          </p>
          <p class="flex">
            <label for="id_engineer"><b>Назначенный инженер:</b></label>
            {{ form.engineer.errors }}
            {{ form.engineer }}
          </p>
        {% endif %}
        {% if not admin and form.engineer.value != request.user.id or data.application.status_id == 4 %}
          <p><b>Статус заявки:</b> {{ data.application.status_name }}</p>
          <p><b>Приоритет заявки:</b> {{ data.application.priority_name }}</p>
          <p><b>Назначенный инженер:</b> {{ data.application.engineer_name }}</p>
        {% endif %}
        <p><b>Контактные данные по заявке:</b> {% if data.application.contact_id %}{{ data.application.contact_name }} <a href="mailto:{{ data.application.contact_email }}">{{ data.application.contact_email }}</a> {{ data.application.contact_phone|default_if_none:'' }}{% endif %}</p>
        <p><b>Уровень поддержки:</b> {{ data.application.support_level }}</p>
        <p><b>Вендор:</b> {{ data.application.vendor_name }}</p>
        <p><b>Оборудование:</b>
          {% if data.application.status_id != 4 %}
            <input type="text" id="id_equipment" name="equipment" list="equipments" placeholder="Введите серийный номер оборудования" autocomplete="off" value="{{ data.application.equipment_name }}" {% if data.application.changed %}readonly="readonly"{% endif %}>
            {% if not data.application.changed %}
              <datalist id="equipments">
              </datalist>
            {% endif %}
          {% else %}
            {{ data.application.equipment_name }}
          {% endif %}
        </p>
        <p><b>Файлы конфигурации:</b></p>
        <div id="confs">
        {% for doc in confs %}
          <p class="pl-30"><a target="_blank" href="{% get_media_prefix %}{{ doc.document }}">{{ doc.filename }}</a></p>
        {% endfor %}
        </div>
        <p><b>Описание проблемы:</b> {{ data.application.problem }}</p>
        <p><b>Прикрепленные файлы:</b></p>
        {{ document.management_form }}
        {% for doc in document %}
          {% if doc.document.value %}
          {{ doc.id }}
          <p class="pl-30">
            <a target="_blank" href="{% get_media_prefix %}{{ doc.document.value }}">{{ doc.name.value }}</a>
            {{ doc.name.as_hidden }}
          {% if data.application.status_id != 4 %}
            <a class="delete-item"></a>
            <input type="checkbox" name="{{ doc.prefix }}-DELETE" id="id_{{ doc.prefix }}-DELETE" class="hidden">
          {% endif %}
          </p>
          {% endif %}
        {% endfor %}
        {% if data.application.status_id != 4 %}
        <div><a id="add-doc" class="add-item"> Добавить файл <span class="red-text">(Возможна загрузка только текстовых форматов, архивов, изображений. Размер файла не должен превышать 50 Мб)</span></a></div>
        <div>
          <button type="submit" class="btn dark-btn">Сохранить</button>
          {% if admin %}<a class="btn red-btn" id="delete-app" app_pk="{{ data.application.id }}">Удалить заявку</a>{% endif %}
        </div>
        {% elif admin %}
          <div><a class="btn red-btn" id="return-app" app_pk="{{ data.application.id }}">Вернуть в работу</a></div>
        {% endif %}
      </form>
    </div>
    {% if form.engineer.value == request.user.id or admin %}
    <div class="w-40 relative">
      {% if data.application.status_id != 4 %}
        <div class="form mb-40">
        <span class="form-label">Запчасти</span>
        <form method="POST">
          {% csrf_token %}
          {{ spares.management_form }}
          <div class="justify-between">
            <input type="text" id="id_spares" list="spares" placeholder="ЗИП" autocomplete="off"> <a id="add-spare" class="add-item"></a>
            <datalist id="spares">
            </datalist>
          </div>
          {% for spare in spares %}
            {{ spare.id }}
              <p class="pl-30 exists" spare="{{ spare.instance.spare_id }}">
              {{ spare.instance.spare }} (S/n: {{ spare.instance.spare.sn }})
              {{ spare.spare.as_hidden }}
              <a class="delete-item"></a>
              <input type="checkbox" name="{{ spare.prefix }}-DELETE" id="id_{{ spare.prefix }}-DELETE" class="hidden">
              </p>
          {% endfor %}
          <div class="justify-center">
            <button type="submit" class="btn dark-btn">Сохранить</button>
          </div>
        </form>
      </div>
      {% endif %}
      <div class="bottom right-from-center"><a class="btn light-btn" href="{% url 'app-history' data.application.id 1 %}">Лог кейса</a></div>
    </div>
    {% endif %}
  </div>
    {% if data.application.status_id != 4 %}
    <div class="justify-between pb-40">
      <div class="form w-50">
        <form method="POST" id="comment-form" action="{% url 'add-app-comm-api' data.application.id %}">
          {% csrf_token %}
          <div>
            {{ comment.text.errors }}
            {{ comment.text.label_tag }}
            {{ comment.text }}
          </div>
          <div>
          {{ comment.hide.label_tag }}
          {{ comment.hide }}
          </div>
          <div class="justify-center">
            <button type="submit" class="btn dark-btn">Отправить</button>
          </div>
        </form>
      </div>

      <div class="form w-40">
        <p class="timeline-title"><a href="{% url 'app-history' data.application.id 0 %}">Действия</a></p>
        <div class="scroll-x">
        <ul class="timeline">
          {% for record in data.history %}
            <li>
              <p><span class="timeline-date">{{ record.formatted_date }}</span> <span class="timeline-user">Пользователь: {{ record.author_name }}</span></p>
              {% if record.record_type == 'comment' and record.hide %}
                <p class="blue-text">Комментарий скрыт от пользователей</p>
              {% endif %}
              <p>{{ record.text|safe }}</p>
            </li>
          {% endfor %}
        </ul>
        </div>
        </div>
    </div>
    {% endif %}
  </div>
  {% if admin %}
  <div id="modal" class="modal">
    <div class="modal-content">
      <div class="modal-text">Вся информация, связанная с заявкой № {{ data.application.id }}, будет удалена. Удалить заявку?</div>
      <div class="modal-buttons"><a class="btn light-btn" id="modal-delete" action="{% url 'edit-application-api' data.application.id %}">Удалить</a><a class="btn light-btn" id="modal-cancel">Отмена</a></div>
    </div>
  </div>

  <div id="return-modal" class="modal">
    <div class="modal-content">
      <div class="modal-text">Вернуть заявку № {{ data.application.id }} в работу?</div>
      <div class="modal-buttons"><a class="btn light-btn" id="modal-return" action="{% url 'edit-done-application-api' data.application.id 6 %}">Вернуть</a><a class="btn light-btn">Отмена</a></div>
    </div>
  </div>
  {% endif %}
  <div class="empty-doc hidden">
      <p class="pl-30">
        {{ document.empty_form.id }}
        {{ document.empty_form.name.as_hidden }}
        {{ document.empty_form.document.errors }}
        {{ document.empty_form.document }}
        <a class="delete-item"></a>
        <input type="checkbox" name="{{ document.empty_form.prefix }}-DELETE" id="id_{{ document.empty_form.prefix }}-DELETE" class="hidden">
      </p>
  </div>
  <div class="empty-spare hidden">
      <p class="pl-30" spare="">
        {{ spares.empty_form.id }}
        {{ spares.empty_form.spare.errors }}
        {{ spares.empty_form.spare.as_hidden }}
         <a class="delete-item"></a>
        <input type="checkbox" name="{{ spares.empty_form.prefix }}-DELETE" id="id_{{ spares.empty_form.prefix }}-DELETE" class="hidden">
      </p>
  </div>
</section>
{% endblock content %}
{% block pagescripts %}
<script type="text/javascript" src="{% static 'ckeditor/ckeditor-init.js' %}"></script>
<script type="text/javascript" src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"></script>
<script type="module" src="{% static 'js/apps_edit.js' %}"></script>
{% endblock %}

templates/applications/installed_base_list.html
{% extends 'admin/change_list.html' %}
{% block object-tools-items %}
  <li><a href="{% url 'installed-base' %}">Экспортировать в Excel</a></li>
  {{ block.super }}
{% endblock %}

templates/applications/new_add.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Оформление заявки{% endblock title %}

{% block page-title %}Оформление заявки{% endblock page-title %}
{% block content %}
<section>
  <div class="container">
    <div class="justify-center">{{ contacts }}
        <input type="hidden" id="back" value="{% url 'app-list' %}">
        <input type="hidden" id="current-user-id" value="{{ request.user.id }}">
      <div class="form">
        <form method="POST" enctype="multipart/form-data" id="app-form" action="{% url 'add-application-api' %}" class="relative">
          {% if permissions.is_staff %}
          <div>
            {{ form.client.errors }}
            {{ form.client.label_tag }}
            <select name="client" id="id_client">
              {% for val, text in form.fields.client.choices %}
                <option value="{{ val }}" {% if val == request.user.id %}selected{% endif %}>{{ text }}</option>
              {% endfor %}
            </select>
          </div>
          {% endif %}
          <div>
            {{ form.priority.errors }}
            {{ form.priority.label_tag }}
            {{ form.priority }}
          </div>
          <div>
            <label for="id_equipment">Оборудование:</label>
            <input type="text" id="id_equipment" name="equipment" placeholder="Введите серийный номер оборудования" autocomplete="off" required>
            <ul id="equipments" class="datalist">
            </ul>
          </div>
          <div>
            {{ form.problem.errors }}
            {{ form.problem.label_tag }}
            {{ form.problem }}
          </div>
          <div>
            {{ form.contact.errors }}
            {{ form.contact.label_tag }}
            {{ form.contact }}
          </div>
          <div class="form-grey-line">Файлы</div>
          <p class="pl-30">
            <input type="file" name="documents">
             <a class="delete-item"></a>
          </p>
          <div><a id="add-doc" class="add-item"> Добавить файл</a></div>
          <div class="justify-center">
            <button id="submit-btn" type="submit" class="btn dark-btn">Отправить</button>
            <a href="{% url 'app-list' %}" class="btn light-btn">Отмена</a>
          </div>
        </form>
      </div>
    </div>
    <div class="empty-doc hidden">
        <p class="pl-30">
          <input type="file" name="documents">
          <a class="delete-item"></a>
        </p>
    </div>
  </div>
  <div id="modal" class="modal">
    <div class="modal-content">
      <div class="modal-text"></div>
      <a class="btn light-btn" id="modal-close">ОК</a>
    </div>
  </div>
</section>
{% endblock content %}
{% block pagescripts %}
<script type="module" src="{% static 'js/applications/add.js' %}"></script>
{% endblock %}

templates/applications/test.html
{% load static %}
<form method="POST" enctype="multipart/form-data" action="{% url 'add-app-docs-api' 160555 %}">
<p>
  <input type="file" name="documents"></p>
<p><input type="file" name="documents"></p></p>
  <button>Отправить</button>
</form>
{% block pagescripts %}
<script type="module" src="{% static 'js/test.js' %}"></script>
{% endblock %}